const Images = {
    BG_1: require('../assets/background/bg1.png'),
    BG_2: require('../assets/background/bg2.png'),
    BG_3: require('../assets/background/bg3.png'),
    BG_4: require('../assets/background/bg4.jpg'),
    BG_5: require('../assets/background/bg5.jpg'),
    BG_6: require('../assets/background/bg6.jpg'),
    DETAILS_BG_3: require('../assets/background/details_bg_1.png'),
    BLUR_BG: require('../assets/background/blur_bg.png'),
    BLUE_WORLD: require('../assets/images/blue-world-theme-park.jpg'),
    BOAT_CLUB: require('../assets/images/boatClub.jpg'),

    COLLEGE: require('../assets/images/college.png'),
    MAP: require('../assets/images/map.png'),
    MAP1: require('../assets/images/map1.png'),
    LOGIN_LOGO: require('../assets/login/logo.png'),
    LOGIN_FOOTER: require('../assets/login/footer.png'),
    METRO: require('../assets/images/metroImg.png'),
    METRO1: require('../assets/images/metro.png'),
    METRO2: require('../assets/images/metro1.png'),
    METRO_MAP: require('../assets/images/kanpurMetroMap.jpg'),
    ZSQUARE: require('../assets/images/z-square-mall.jpg'),
    NANA_RAO_PARK: require('../assets/images/nana-rao-park.jpg'),
    KAMLA_RETREAT: require('../assets/images/kamla-retreat.jpg'),
    GREEN_PARK: require('../assets/images/green-park-stadium.jpg'),
    GANGA_BARRAGE: require('../assets/images/ganga-barrage.jpg'),
    ISKCON: require('../assets/images/iskcon-temple-kanpur.jpg'),
    BITHOOR: require('../assets/images/bithoor.jpg'),
    ZOO: require('../assets/images/zoo.jpg'),
    JAPANI_GARDEN: require('../assets/images/japani-garden-kanpur.jpg'),
    KANPUR_MEMORIAL_CHURCH: require('../assets/images/kanpur-memorial-church.jpg'),
    PHOOL_BAGH: require('../assets/images/phool-bagh-and-kanpur-museum.jpg'),
    ARROW: require('../assets/images/arrow.png'),
    imageGallery: require('../assets/images/imageGallery.png'),
    ACCOMMODATION_CARD: require('../assets/CardImg/Hotel.png'),
    ATM_CARDIMG: require('../assets/CardImg/atmLogo.png'),
    BANK_CARDIMG: require('../assets/CardImg/axisLogo.png'),
    ALLAHABADBANK_CARDIMG: require('../assets/CardImg/Allahabad_BankLogo.jpeg'),
    BOIBANK_CARDIMG: require('../assets/CardImg/BANKINDIA_Logo.png'),
    SBIBANK_CARDIMG: require('../assets/CardImg/SBI_logo.png'),
    BOBBANK_CARDIMG: require('../assets/CardImg/BoB_Logo.png'),
    CANRABANK_CARDIMG: require('../assets/CardImg//canraBank_Logo.png'),
    CBOIBANK_CARDIMG: require('../assets/CardImg/CBOI_Logo.png'),
    HDFCBANK_CARDIMG: require('../assets/CardImg/HDFC_Bank_Logo.jpg'),
    ICICIBANK_CARDIMG: require('../assets/CardImg/IciciBankLogo.png'),
    INDIANBANK_CARDIMG: require('../assets/CardImg/INDIANBank_Logo.png'),
    MAHARASHTRABANK_CARDIMG: require('../assets/CardImg/maharashtraBankLogo.png'),
    PNBBANK_CARDIMG: require('../assets/CardImg/PNB_Logo.png'),
    UCOBANKCARDIMG: require('../assets/CardImg/UcoBankLogo.png'),
    UNIONBANK_CARDIMG: require('../assets/CardImg/UnionBank_Logo.png'),

    BUS_STATION_CARDIMG: require('../assets/CardImg/BusStation.png'),
    CINEMA_CARDIMG: require('../assets/CardImg/Cinema.png'),
    COMMON_CARDIMG: require('../assets/CardImg/hospital_logo.png'),
    COMPLEX_CARDIMG: require('../assets/CardImg/foodlogo.png'),
    CSC_CARDIMG: require('../assets/CardImg/foodlogo.png'),
    ELECTRICITY_CARDIMG: require('../assets/CardImg/electricitylogo.png'),
    EMERGENCY_CARDIMG: require('../assets/CardImg/police.png'),
    EVENT_CARDIMG: require('../assets/CardImg/event.png'),
    FOOD_BEVARAGE_CARDIMG: require('../assets/CardImg/foodlogo.png'),
    HOSPITAL_CARDIMG: require('../assets/CardImg/hospital_logo.png'),
    MEDICAL_STORE_CARDIMG: require('../assets/CardImg/chemist.png'),
    MONUMENTS_CARDIMG: require('../assets/CardImg/temple_logo.png'),
    PARKS_CARDIMG: require('../assets/CardImg/Park.png'),
    PAYTAX_CARDIMG: require('../assets/CardImg/electricity.png'),
    POLICE_STATION_CARDIMG: require('../assets/CardImg/policelogo.png'),
    POSTOFFICE_CARDIMG: require('../assets/CardImg/PostOfficeLogo.png'),
    PUBLIC_TOILET_FINDER_CARDIMG: require('../assets/CardImg/toilet.png'),
    RAILWAY_STATION_CARDIMG: require('../assets/CardImg/RailwayStation.png'),
    COLLEGE_CARDIMG: require('../assets/CardImg/vssdcollegelogo.png'),
    PROFILE: require('../assets/images/user.png'),
    KNP_HEADER: require('../assets/images/kanpurHeaderEn.png'),
    KNP_HEADER_HI: require('../assets/images/kanpurHeaderHi.png'),
    DASHBOARD_CIRCLE: require('../assets/images/dashboardCenter.png'),
    SOS:require('../assets/images/SOS.png'),
    TRENDS:require('../assets/images/trendsLogo.png'),
    MODAL_IMAGE:require('../assets/images/vipul_goyal.jpeg'),
    TRANSLATE_lOGO:require('../assets/images/translateLogo.png'),
    TREND_LOGO:require('../assets/images/trends1.png'),

    DASHBOARD_IMAGE_VIEW1:require('../assets/dashboardImages/sports_1.jpeg'),
    DASHBOARD_IMAGE_VIEW2:require('../assets/dashboardImages/sports_2.jpeg'),
    DASHBOARD_IMAGE_VIEW3:require('../assets/dashboardImages/sports_3.jpeg'),
    DASHBOARD_IMAGE_VIEW4:require('../assets/dashboardImages/sports_4.jpeg'),
    DASHBOARD_IMAGE_VIEW5:require('../assets/dashboardImages/sports_5.jpeg'),
    DASHBOARD_IMAGE_VIEW6:require('../assets/dashboardImages/sports_6.jpeg'),
    DASHBOARD_IMAGE_VIEW7:require('../assets/dashboardImages/sports_7.jpeg'),
    DASHBOARD_IMAGE_VIEW8:require('../assets/dashboardImages/sports_8.jpeg'),
    DASHBOARD_IMAGE_VIEW9:require('../assets/dashboardImages/sports_9.jpeg'),
    DASHBOARD_IMAGE_VIEW10:require('../assets/dashboardImages/sports_10.jpeg'),

    NANARAO_PARK1:require('../assets/dashboardImages/nana-rao-park.jpg'),
    NANARAO_PARK2:require('../assets/dashboardImages/nana-rao-park_1.jpg'),
    NANARAO_PARK3:require('../assets/dashboardImages/nana-rao-fort_2.jpg'),

    DASHBOARD_IMAGE_VIEW11:require('../assets/dashboardImages/convention/convention_1.png'),
    DASHBOARD_IMAGE_VIEW12:require('../assets/dashboardImages/convention/convention_2.jpg'),
    DASHBOARD_IMAGE_VIEW13:require('../assets/dashboardImages/convention/convention_3.jpg'),
    DASHBOARD_IMAGE_VIEW14:require('../assets/dashboardImages/convention/convention_4.jpg'),
    DASHBOARD_IMAGE_VIEW15:require('../assets/dashboardImages/convention/convention_5.jpg'),
    DASHBOARD_IMAGE_VIEW16:require('../assets/dashboardImages/convention/convention_6.jpg'),
    DASHBOARD_IMAGE_VIEW17:require('../assets/dashboardImages/convention/convention_7.jpg'),
    DASHBOARD_IMAGE_VIEW18:require('../assets/dashboardImages/convention/convention_8.jpg'),
    DASHBOARD_IMAGE_VIEW19:require('../assets/dashboardImages/convention/convention_9.jpg'),
    DASHBOARD_IMAGE_VIEW20:require('../assets/dashboardImages/convention/convention_10.jpg'),
    DASHBOARD_IMAGE_VIEW21:require('../assets/dashboardImages/convention/convention_11.jpg'),
    DASHBOARD_IMAGE_VIEW22:require('../assets/dashboardImages/convention/convention_12.jpg'),
    DASHBOARD_IMAGE_VIEW23:require('../assets/dashboardImages/convention/convention_13.jpg'),
    DASHBOARD_IMAGE_VIEW24:require('../assets/dashboardImages/convention/convention_14.jpg'),
    DASHBOARD_IMAGE_VIEW25:require('../assets/dashboardImages/convention/convention_15.jpg'),
    DASHBOARD_IMAGE_VIEW26:require('../assets/dashboardImages/convention/convention_16.jpg'),
    
    GREENPARK_IMAGE_VIEW1:require('../assets/dashboardImages/green_park/green_park_1.jpg'),
    GREENPARK_IMAGE_VIEW2:require('../assets/dashboardImages/green_park/green_park_11.jpg'),
    GREENPARK_IMAGE_VIEW3:require('../assets/dashboardImages/green_park/green_park_3.jpg'),
    GREENPARK_IMAGE_VIEW4:require('../assets/dashboardImages/green_park/green_park_4.jpg'),
    GREENPARK_IMAGE_VIEW5:require('../assets/dashboardImages/green_park/green_park_5.jpg'),
    GREENPARK_IMAGE_VIEW6:require('../assets/dashboardImages/green_park/green_park_6.jpg'),
    GREENPARK_IMAGE_VIEW7:require('../assets/dashboardImages/green_park/green_park_7.jpg'),
    GREENPARK_IMAGE_VIEW8:require('../assets/dashboardImages/green_park/green_park_8.jpg'),
    GREENPARK_IMAGE_VIEW9:require('../assets/dashboardImages/green_park/green_park_9.jpg'),
    GREENPARK_IMAGE_VIEW10:require('../assets/dashboardImages/green_park/green_park_10.jpg'),
  
}

export default Images;